// Each foreground is clipped from its own final scene. Both images share the
// same source, viewport and geometry; revealing the background cannot move the lamp.
export function initElbaCard(card){
 const stage=card.querySelector('[data-elba-stage]');if(!stage||!stage.querySelector('.elba-composition'))return{start(){},stop(){},inspect:()=>({running:false,needsBuild:true})};
 const exhibits=[...card.querySelectorAll('[data-elba-exhibit]')],buttons=[...card.querySelectorAll('[data-elba-select]')],modes=exhibits.map(e=>e.dataset.elbaExhibit);
 const tour=card.querySelector('[data-elba-tour]'),counter=card.querySelector('[data-elba-count]'),timers=new Set(),cache=new Map(),imageTokens=new WeakMap();
 let running=false,reduced=false,current=modes[0],phase='product',automatic=true,requested=null,theme=document.documentElement.dataset.theme==='day'?'day':'night',request=0;
 const timing={product:1800,reveal:650,tour:8000};
 const clear=()=>{timers.forEach(clearTimeout);timers.clear();};
 const later=(delay,fn)=>{const id=setTimeout(()=>{timers.delete(id);if(running&&!document.hidden)fn();},delay);timers.add(id);return id;};
 const setPhase=value=>{phase=value;card.dataset.elbaPhase=value;};
 function syncTour(){const playing=running&&automatic&&!reduced;tour.disabled=reduced;tour.setAttribute('aria-pressed',String(playing));tour.setAttribute('aria-label',playing?'Wstrzymaj automatyczny pokaz opraw ELBA':'Uruchom automatyczny pokaz opraw ELBA');tour.querySelector('span').textContent=playing?'Pauza':'Odtwórz';card.dataset.elbaTour=playing?'playing':'paused';}
 function sync(){card.dataset.elbaMode=current;exhibits.forEach(e=>{const active=e.dataset.elbaExhibit===current;e.classList.toggle('is-selected',active);e.setAttribute('aria-hidden',String(!active));});buttons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.elbaSelect===current)));counter.textContent='0'+(modes.indexOf(current)+1)+' / 05';}
 function decode(src){if(!cache.has(src)){const im=new Image();im.src=src;cache.set(src,im.decode().then(()=>true).catch(()=>{cache.delete(src);return false;}));}return cache.get(src);}
 async function loadImage(exhibit){const tag=(imageTokens.get(exhibit)||0)+1;imageTokens.set(exhibit,tag);const layers=[...exhibit.querySelectorAll('.elba-composition image')];const src=layers[0].getAttribute('data-elba-'+theme);const ok=await decode(src);if(imageTokens.get(exhibit)!==tag)return false;if(ok)layers.forEach(layer=>layer.setAttribute('href',src));return ok;}
 function present(){clear();requested=null;card.dataset.elbaSwitching='false';sync();setPhase(reduced?'installed':'product');syncTour();if(!running||reduced)return;later(timing.product,()=>setPhase('reveal'));later(timing.product+timing.reveal,()=>setPhase('installed'));if(automatic)later(timing.tour,()=>select(modes[(modes.indexOf(current)+1)%modes.length],false));}
 async function select(mode,manual=true){
  if(!modes.includes(mode))return;if(manual)automatic=false;
  if(mode===current&&!requested){clear();syncTour();if(running&&(phase==='product'||(manual&&phase==='installed')))present();else if(running&&phase==='reveal')later(timing.reveal,()=>setPhase('installed')); return;}
  const tag=++request;requested=mode;clear();syncTour();card.dataset.elbaSwitching='true';buttons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.elbaSelect===mode)));
  await loadImage(exhibits[modes.indexOf(mode)]);if(tag!==request)return;current=mode;present();
 }
 buttons.forEach((button,index)=>{button.disabled=false;button.addEventListener('pointerenter',e=>{if(e.pointerType!=='touch')select(button.dataset.elbaSelect);});button.addEventListener('focus',()=>select(button.dataset.elbaSelect));button.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();select(button.dataset.elbaSelect);});button.addEventListener('keydown',e=>{const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:['ArrowRight','ArrowDown'].includes(e.key)?(index+1)%buttons.length:['ArrowLeft','ArrowUp'].includes(e.key)?(index+buttons.length-1)%buttons.length:null;if(next!==null){e.preventDefault();buttons[next].focus();}});});
 tour.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();automatic=!automatic;if(automatic)present();else{clear();setPhase('installed');syncTour();}});
 addEventListener('prescot:themechange',e=>{theme=e.detail?.theme==='day'?'day':'night';card.dataset.elbaTheme=theme;exhibits.forEach(loadImage);});
 const geometry=()=>{const active=exhibits[modes.indexOf(current)],svg=active.querySelector('svg'),path=active.querySelector('[data-elba-silhouette]'),box=path.getBBox(),matrix=svg.getScreenCTM();const point=(x,y)=>({x:matrix.a*x+matrix.c*y+matrix.e,y:matrix.b*x+matrix.d*y+matrix.f});const a=point(box.x,box.y),b=point(box.x+box.width,box.y+box.height);return{foreground:active.querySelector('.elba-fixed-product').getAttribute('href'),background:active.querySelector('.elba-background-frame').getAttribute('href'),viewBox:svg.getAttribute('viewBox'),productScreenBounds:{x:a.x,y:a.y,width:b.x-a.x,height:b.y-a.y},canvas:JSON.parse(JSON.stringify(svg.getBoundingClientRect())),foregroundTransform:getComputedStyle(active.querySelector('.elba-fixed-product')).transform,backgroundTransform:getComputedStyle(active.querySelector('.elba-background-frame')).transform};};
 sync();setPhase('product');card.dataset.elbaSwitching='false';card.dataset.elbaTheme=theme;card.dataset.elbaReduced='false';card.classList.add('elba-ready');syncTour();exhibits.forEach(loadImage);
 return{start(options={}){if(running)return;running=true;reduced=!!options.reduced;card.dataset.elbaReduced=String(reduced);card.classList.add('elba-active');present();},stop(){running=false;clear();request++;requested=null;card.dataset.elbaSwitching='false';card.classList.remove('elba-active');setPhase('product');sync();syncTour();},select,inspect:()=>({running,reduced,mode:current,requested,phase,automatic,pending:timers.size,theme,hudVisible:reduced||phase==='product',timing,...geometry()})};
}
