// Catalogue values checked against original product cards on 2026-09-24.
// 3w1 uses common +24 V and one selected negative terminal, L/M/H.
export const evolutionModels=[
 {
  "voltage": "24",
  "cut": "50",
  "density": "160",
  "tech": "2835",
  "power": "3",
  "family": "delux3",
  "sku": "24D160-11-3080-1010",
  "color": "3000",
  "unit": "K",
  "colorCopy": "Ciepła biel",
  "techLabel": "SMD / DELUX 3w1",
  "index": "01 / DELUX 3w1",
  "title": "Trzy moce.<br>Jedna taśma.",
  "copy": "Wspólny +24 V i pole −L. LOW daje 3 W/m do subtelnego podświetlenia. Moc wybierasz podczas podłączenia.",
  "ink": "#e9c395",
  "hue": 34,
  "light": "#ffbd77",
  "width": "10",
  "ip": "IP20",
  "beam": "120",
  "output": "460",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ / LOW",
  "quality": "> 80",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "detail": "SMD 2,8 × 3,5 mm",
  "pdf": "bf03bcaa9b15afb6",
  "mode": 0,
  "nav": "LOW",
  "navFamily": "3w1 · 24 V",
  "dwell": 1.6,
  "dayInk": "#835728"
 },
 {
  "voltage": "24",
  "cut": "50",
  "density": "160",
  "tech": "2835",
  "power": "6",
  "family": "delux3",
  "sku": "24D160-11-3080-1010",
  "color": "3000",
  "unit": "K",
  "colorCopy": "Ciepła biel",
  "techLabel": "SMD / DELUX 3w1",
  "index": "02 / DELUX 3w1",
  "title": "Więcej światła.<br>Ten sam detal.",
  "copy": "Podłącz +24 V oraz −M. MEDIUM to 6 W/m i 930 lm/m — środkowy poziom mocy tej samej taśmy.",
  "ink": "#e9c395",
  "hue": 34,
  "light": "#ffbd77",
  "width": "10",
  "ip": "IP20",
  "beam": "120",
  "output": "930",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ / MEDIUM",
  "quality": "> 80",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "detail": "SMD 2,8 × 3,5 mm",
  "pdf": "bf03bcaa9b15afb6",
  "mode": 1,
  "nav": "MEDIUM",
  "navFamily": "3w1 · 24 V",
  "dwell": 1.3,
  "dayInk": "#66603d"
 },
 {
  "voltage": "24",
  "cut": "50",
  "density": "160",
  "tech": "2835",
  "power": "11",
  "family": "delux3",
  "sku": "24D160-11-3080-1010",
  "color": "3000",
  "unit": "K",
  "colorCopy": "Ciepła biel",
  "techLabel": "SMD / DELUX 3w1",
  "index": "03 / DELUX 3w1",
  "title": "Pełna moc.<br>Wyraźna linia.",
  "copy": "Podłącz +24 V oraz −H. HIGH daje 11 W/m i 1750 lm/m. Cztery pola, trzy sposoby podłączenia.",
  "ink": "#e9c395",
  "hue": 34,
  "light": "#ffbd77",
  "width": "10",
  "ip": "IP20",
  "beam": "120",
  "output": "1750",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ / HIGH",
  "quality": "> 80",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "detail": "SMD 2,8 × 3,5 mm",
  "pdf": "bf03bcaa9b15afb6",
  "mode": 2,
  "nav": "HIGH",
  "navFamily": "3w1 · 24 V",
  "dwell": 1.5,
  "dayInk": "#356a7c"
 },
 {
  "voltage": "24",
  "cut": "50",
  "density": "160",
  "tech": "2835",
  "power": "11",
  "family": "delux3",
  "sku": "24D160-11-4080-1010",
  "color": "4000",
  "unit": "K",
  "colorCopy": "Neutralna biel",
  "techLabel": "SMD / DELUX 3w1",
  "index": "04 / DELUX 3w1",
  "title": "Biel do<br>codzienności.",
  "copy": "Ta sama swoboda wyboru mocy, teraz w neutralnej bieli 4000 K. Dobierz poziom światła do swojego wnętrza.",
  "ink": "#e4ddbd",
  "hue": 47,
  "light": "#fff0d0",
  "width": "10",
  "ip": "IP20",
  "beam": "120",
  "output": "1800",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ / HIGH",
  "quality": "> 80",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "detail": "SMD 2,8 × 3,5 mm",
  "pdf": "b3f1d3176fefb64b",
  "mode": 2,
  "nav": "4000 K",
  "navFamily": "3w1 · 24 V",
  "dayInk": "#775095",
  "dwell": 1.1
 },
 {
  "voltage": "24",
  "cut": "66",
  "density": "128",
  "tech": "2835",
  "power": "11,5",
  "family": "smd",
  "sku": "24D009-063-10-W57",
  "color": "5700",
  "unit": "K",
  "colorCopy": "Chłodna biel",
  "techLabel": "SMD / DELUX",
  "index": "05 / DELUX",
  "title": "DELUX.<br>Światło z Polski.",
  "copy": "24 V, 128 diod na metr i chłodna biel 5700 K. Polska seria DELUX do precyzyjnie dobranej linii światła.",
  "ink": "#d5e6e5",
  "hue": 183,
  "light": "#e4f3ff",
  "width": "10",
  "ip": "IP20",
  "beam": "120",
  "output": "1570",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ ŚWIATŁA",
  "quality": "> 80",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "detail": "SMD 2,8 × 3,5 mm",
  "pdf": "0d0dde32ccd197cb",
  "nav": "5700 K",
  "navFamily": "DELUX · 24 V",
  "dayInk": "#835728",
  "dwell": 1.1
 },
 {
  "sku": "24DS004-050-4-NW",
  "family": "slim",
  "color": "4000",
  "unit": "K",
  "colorCopy": "Neutralna biel",
  "tech": "2835",
  "techLabel": "SMD / DELUX SLIM",
  "density": "160",
  "power": "6,5",
  "voltage": "24",
  "cut": "50",
  "width": "4",
  "index": "06 / DELUX SLIM",
  "title": "Mniej miejsca.<br>Pełnia światła.",
  "copy": "Tylko 4 mm szerokości. 160 diod na metr i 1050 lm/m w neutralnej bieli — do wąskich detali i mebli.",
  "ink": "#d8e2ce",
  "hue": 104,
  "light": "#fff0d0",
  "output": "1050",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ ŚWIATŁA",
  "quality": "> 80",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "detail": "PCB 4 mm · SMD 2,8 × 3,5 mm",
  "pdf": "11a70176f6b14349",
  "ip": "IP20",
  "beam": "120",
  "nav": "4 mm",
  "navFamily": "SLIM · 24 V",
  "dayInk": "#66603d",
  "dwell": 1.1
 },
 {
  "sku": "W-E007-017-8-NW",
  "family": "smd5",
  "width": "8",
  "voltage": "5",
  "density": "60",
  "cut": "17",
  "tech": "2835",
  "techLabel": "SMD / PREMIUM",
  "color": "4000",
  "unit": "K",
  "colorCopy": "Neutralna biel",
  "power": "3,4",
  "output": "290",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ ŚWIATŁA",
  "quality": "8",
  "qualityUnit": "mm",
  "qualityLabel": "SZEROKOŚĆ PCB",
  "ip": "IP20",
  "beam": "120",
  "detail": "SMD 2,8 × 3,5 mm",
  "pdf": "3496b10a857c3f8f",
  "title": "Małe napięcie.<br>Światło w detalu.",
  "copy": "PREMIUM 5 V DC: 3,4 W/m i 60 diod na metr. Płytka 8 mm z podziałem co 17 mm do niewielkich instalacji.",
  "ink": "#e4ddbd",
  "hue": 47,
  "light": "#fff0d0",
  "dayInk": "#706039",
  "nav": "4000 K",
  "navFamily": "PREMIUM · 5 V",
  "index": "07 / PREMIUM",
  "dwell": 1.1
 },
 {
  "sku": "12E60-5-2790-85",
  "family": "smd12",
  "width": "8",
  "voltage": "12",
  "density": "60",
  "cut": "50",
  "tech": "2835",
  "techLabel": "SMD / PREMIUM",
  "color": "2700",
  "unit": "K",
  "colorCopy": "Ciepła biel",
  "power": "5",
  "output": "500",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ ŚWIATŁA",
  "quality": ">80",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "ip": "IP20",
  "beam": "120",
  "detail": "SMD 2,8 × 3,5 mm",
  "pdf": "6a94be9779fc0b4f",
  "title": "Ciepło<br>w każdym punkcie.",
  "copy": "PREMIUM SMD 12 V. Biel 2700 K, moc 5 W/m i moduł cięcia 50 mm — ciepłe światło do mebli i wnęk.",
  "ink": "#ecc28d",
  "hue": 32,
  "light": "#ffbd77",
  "dayInk": "#8a5e2c",
  "nav": "2700 K",
  "navFamily": "PREMIUM · 12 V",
  "index": "08 / PREMIUM",
  "dwell": 1.1
 },
 {
  "sku": "24E009-050-8-NW",
  "family": "smd24",
  "width": "8",
  "voltage": "24",
  "density": "120",
  "cut": "50",
  "tech": "2835",
  "techLabel": "SMD / PREMIUM",
  "color": "4000",
  "unit": "K",
  "colorCopy": "Neutralna biel",
  "power": "10",
  "output": "1200",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ ŚWIATŁA",
  "quality": ">80",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "ip": "IP20",
  "beam": "120",
  "detail": "SMD 2,8 × 3,5 mm",
  "pdf": "92ea540da50f8d19",
  "title": "Codzienne światło.<br>Wersja 24 V.",
  "copy": "PREMIUM SMD 24 V: 120 diod na metr, 10 W/m i 1200 lm/m. Neutralna biel na płytce o szerokości 8 mm.",
  "ink": "#e4ddbd",
  "hue": 47,
  "light": "#fff0d0",
  "dayInk": "#706039",
  "nav": "4000 K",
  "navFamily": "PREMIUM · 24 V",
  "index": "09 / PREMIUM",
  "dwell": 1.1
 },
 {
  "sku": "EF018-050-6-WW",
  "family": "sshape",
  "color": "3000",
  "unit": "K",
  "colorCopy": "Ciepła biel",
  "tech": "2835",
  "techLabel": "SMD / PREMIUM S-SHAPE",
  "density": "60",
  "power": "10,8",
  "voltage": "12",
  "cut": "50",
  "width": "6",
  "index": "10 / PREMIUM S-SHAPE",
  "title": "Światło zmienia<br>kierunek.",
  "copy": "Wycięcia w płytce pozwalają prowadzić taśmę po łukach w jej płaszczyźnie. 6 mm szerokości do liter, znaków i detali.",
  "ink": "#edcb9f",
  "hue": 37,
  "light": "#ffd09a",
  "output": "900",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ ŚWIATŁA",
  "quality": "> 80",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "detail": "Profilowane PCB · SMD 2835",
  "pdf": "35a9a1d23c66ee72",
  "ip": "IP20",
  "beam": "120",
  "nav": "6 mm",
  "navFamily": "S-Shape · 12 V",
  "dayInk": "#66603d",
  "dwell": 1.1
 },
 {
  "sku": "E024-050-10-RGB",
  "family": "rgb",
  "color": "RGB",
  "unit": "",
  "colorCopy": "Czerwień. Zieleń. Błękit.",
  "tech": "5050",
  "techLabel": "SMD / PREMIUM RGB",
  "density": "60",
  "power": "12",
  "voltage": "12",
  "cut": "50",
  "index": "11 / PREMIUM RGB",
  "title": "Kolor zgodny<br>z pomysłem.",
  "copy": "Trzy kanały RGB w diodzie 5050. Dobierz sterownik i zmieniaj kolor oraz jasność instalacji.",
  "ink": "#d1b6eb",
  "hue": 274,
  "light": "#cb84ff",
  "width": "10",
  "ip": "IP20",
  "beam": "120",
  "output": "180",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ ŚWIATŁA",
  "quality": "3",
  "qualityUnit": "kanały",
  "qualityLabel": "STEROWANIE RGB",
  "detail": "SMD 5,0 × 5,0 mm",
  "pdf": "456fd9db757091a7",
  "nav": "RGB",
  "navFamily": "5050 · 12 V",
  "dwell": 1.4,
  "dayInk": "#356a7c"
 },
 {
  "sku": "24EC528-045-10-WW",
  "family": "cob",
  "color": "3000",
  "unit": "K",
  "colorCopy": "Ciepła linia światła",
  "tech": "COB",
  "techLabel": "PREMIUM / COB",
  "density": "528",
  "power": "14",
  "voltage": "24",
  "cut": "45",
  "index": "12 / PREMIUM COB",
  "title": "Punkty stają się<br>jedną linią.",
  "copy": "528 diod na metr pod wspólną warstwą luminoforu. Ciepła biel 3000 K płynie przez całą długość taśmy.",
  "ink": "#e7cba3",
  "hue": 38,
  "light": "#ffd29a",
  "width": "10",
  "ip": "IP20",
  "beam": "120",
  "output": "120",
  "outputUnit": "°",
  "outputLabel": "KĄT ŚWIECENIA",
  "quality": "> 90",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "detail": "Wspólna warstwa luminoforu",
  "pdf": "6cb32a0fdbd7f125",
  "nav": "3000 K",
  "navFamily": "COB · 24 V",
  "dwell": 1.45,
  "dayInk": "#775095"
 },
 {
  "sku": "48EC480-050-8-NW",
  "family": "cob48",
  "width": "8",
  "voltage": "48",
  "density": "480",
  "cut": "50",
  "tech": "COB",
  "techLabel": "PREMIUM / COB",
  "color": "4000",
  "unit": "K",
  "colorCopy": "Neutralna biel",
  "power": "8,2",
  "output": "760",
  "outputUnit": "lm/m",
  "outputLabel": "STRUMIEŃ ŚWIATŁA",
  "quality": "90",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "ip": "IP20",
  "beam": "180",
  "detail": "Ciągły luminofor · 180°",
  "pdf": "bf2ca55deb0c5d89",
  "title": "Linia światła.<br>Teraz 48 V.",
  "copy": "COB 48 V, 480 diod na metr i kąt świecenia 180°. Neutralna biel 4000 K, płytka 8 mm i moc 8,2 W/m.",
  "ink": "#e4ddbd",
  "hue": 47,
  "light": "#fff0d0",
  "dayInk": "#706039",
  "nav": "4000 K",
  "navFamily": "COB · 48 V",
  "dwell": 1.6,
  "index": "13 / PREMIUM COB"
 },
 {
  "sku": "24EC528-045-10-W",
  "family": "cob",
  "color": "6500",
  "unit": "K",
  "colorCopy": "Chłodna linia światła",
  "tech": "COB",
  "techLabel": "PREMIUM / COB",
  "density": "528",
  "power": "14",
  "voltage": "24",
  "cut": "45",
  "index": "14 / PREMIUM COB",
  "title": "Twoja linia.<br>Twój system.",
  "copy": "COB w chłodnej bieli 6500 K. Taśma, zasilanie, sterowanie i profil — elementy jednego systemu.",
  "ink": "#c7e2ed",
  "hue": 196,
  "light": "#d0e7ff",
  "width": "10",
  "ip": "IP20",
  "beam": "120",
  "output": "120",
  "outputUnit": "°",
  "outputLabel": "KĄT ŚWIECENIA",
  "quality": "> 90",
  "qualityUnit": "Ra",
  "qualityLabel": "ODDAWANIE BARW",
  "detail": "Wspólna warstwa luminoforu",
  "pdf": "6cb32a0fdbd7f125",
  "nav": "6500 K",
  "navFamily": "COB · 24 V",
  "dwell": 1.2,
  "dayInk": "#66603d"
 }
];

const boundaries=[0],total=evolutionModels.reduce((sum,m)=>sum+m.dwell,0);
evolutionModels.forEach(m=>boundaries.push(boundaries.at(-1)+m.dwell/total));
export const introEnd=0;
export const modelChapterProgress=evolutionModels.map((_,i)=>i===0?0:boundaries[i]+(boundaries[i+1]-boundaries[i])*.16);
export const chapterProgress=modelChapterProgress.map(p=>introEnd+(1-introEnd)*p);
export const storyProgress=p=>Math.max(0,Math.min(1,(p-introEnd)/(1-introEnd)));
export function evolutionState(p){
 p=Math.max(0,Math.min(1,p));let from=0;
 while(from<evolutionModels.length-1&&p>=boundaries[from+1])from++;
 const local=(p-boundaries[from])/(boundaries[from+1]-boundaries[from]);
 const raw=Math.max(0,Math.min(1,(local-.66)/.34)),blend=raw*raw*(3-2*raw);
 return{from,to:Math.min(evolutionModels.length-1,from+1),blend:from===evolutionModels.length-1?0:blend,local};
}
export const modelIndex=p=>{const s=evolutionState(p);return s.blend>=.5?s.to:s.from;};
