export const origin = 'https://bohunek5.github.io/prescotled/';
export const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const routes = [
 ['tasmy-led','Taśmy LED'], ['zasilacze','Zasilacze PR-MAD'], ['sterowniki','Sterowniki'],
 ['zastosowania','Zastosowania'], ['produkcja','Produkcja i laboratorium'],
 ['dystrybucja','Dystrybucja'], ['do-pobrania','Do pobrania'], ['kontakt','Kontakt'], ['konfigurator','Konfigurator 3D']
];
export function header(prefix = '', active = '') {
 const link = (route, label) => `<a href="${prefix}${route}/"${active === route ? ' aria-current="page"' : ''}>${label}</a>`;
 return `<header class="site-header"><a class="brand" href="${prefix || './'}" aria-label="PRESCOT LED — strona główna"><img src="${prefix}assets/logo.svg" alt="PRESCOT LED" width="488" height="80"></a><nav id="site-nav" aria-label="Menu główne"><a class="nav-home" href="${prefix || './'}"${active === 'home' ? ' aria-current="page"' : ''}>Strona główna</a><details class="nav-group"${['tasmy-led','zasilacze','sterowniki'].includes(active) ? ' data-current="true"' : ''}><summary>Produkty <span aria-hidden="true">⌄</span></summary><div class="nav-dropdown">${routes.slice(0,3).map(([r,l])=>link(r,l)).join('')}</div></details>${link('zastosowania','Zastosowania')}<details class="nav-group"${['produkcja','dystrybucja'].includes(active) ? ' data-current="true"' : ''}><summary>O firmie <span aria-hidden="true">⌄</span></summary><div class="nav-dropdown">${link('produkcja','Produkcja i laboratorium')}${link('dystrybucja','Marki w dystrybucji')}</div></details>${link('do-pobrania','Do pobrania')}${link('kontakt','Kontakt')}</nav><a class="header-config" href="${prefix}konfigurator/"${active === 'konfigurator' ? ' aria-current="page"' : ''}>Konfigurator <span aria-hidden="true">→</span></a><button class="menu-toggle" type="button" aria-controls="site-nav" aria-expanded="false" aria-label="Otwórz menu"><span></span><span></span></button></header>`;
}
export function footer(prefix = '') {
 return `<footer class="site-footer section-shell"><div class="footer-top"><a href="${prefix || './'}" aria-label="PRESCOT LED — strona główna"><img src="${prefix}assets/logo.svg" alt="PRESCOT LED" width="488" height="80"></a><p>Projektujemy. Produkujemy. Mierzymy światło.</p><a href="#main">Do góry ↑</a></div><nav class="footer-nav" aria-label="Menu w stopce">${routes.map(([r,l])=>`<a href="${prefix}${r}/">${l}</a>`).join('')}</nav><div class="footer-bottom"><span>© <span data-year>2026</span> PRESCOT LED</span><a href="https://prescot.pl/polityka-prywatnosci/" target="_blank" rel="noopener">Prywatność · prescot.pl ↗</a><a href="${prefix}do-pobrania/#gwarancja">Warunki gwarancji</a></div></footer>`;
}
export function head(title, description, route, prefix = '../') {
 return `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · PRESCOT LED</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#faf9f6"><link rel="canonical" href="${origin}${route}"><meta property="og:title" content="${esc(title)} · PRESCOT LED"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${origin}assets/hero-tape.webp"><meta property="og:url" content="${origin}${route}"><link rel="icon" href="${prefix}assets/d-pattern.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}style.css?v=4"><link rel="stylesheet" href="${prefix}navigation.css?v=4"><link rel="stylesheet" href="${prefix}components.css?v=1"><link rel="stylesheet" href="${prefix}products3d.css?v=1"><script type="importmap">{"imports":{"three":"https://bohunek5.github.io/prescotpl/konfigurator/vendor/three/build/three.module.min.js","three/addons/":"https://bohunek5.github.io/prescotpl/konfigurator/vendor/three/examples/jsm/"}}</script><script type="module" src="${prefix}app.js?v=4"></script>`;
}
export function breadcrumbs(label, prefix = '../') {
 return `<nav class="breadcrumbs page-breadcrumbs section-shell" aria-label="Okruszki"><a href="${prefix}">Strona główna</a><span aria-hidden="true">/</span><span aria-current="page">${esc(label)}</span></nav>`;
}
